name: deploy-dev

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deploy-dev
      run: |
        export PUSH_TOKEN=${{ secrets.PUSH_TOKEN }}
        ./push.sh
